name 'dhoppe-sudo'
version '0.0.10'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-sudo'
source 'git://github.com/dhoppe/puppet-sudo'
summary 'Sudo Module'
description 'Sudo Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
